package bindgen

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
)

type Writer struct {
	W io.Writer

	Outputs []File
	Index   int
}

func NewFileWriter(outputs []File, index int) (*Writer, error) {
	err := os.MkdirAll(filepath.Dir(outputs[index].Path), 0750)
	if err != nil {
		return nil, err
	}

	file, err := os.Create(outputs[index].Path)
	if err != nil {
		return nil, err
	}

	_, _ = fmt.Fprintf(file, "mod %s;\n\n", outputs[index].Module)

	_, _ = fmt.Fprint(file, "// ----------------------------------------\n")
	_, _ = fmt.Fprint(file, "// | This file is automatically generated |\n")
	_, _ = fmt.Fprint(file, "// ----------------------------------------\n")

	return &Writer{
		W:       file,
		Outputs: outputs,
		Index:   index,
	}, nil
}

func (w *Writer) Write(format string, args ...any) {
	_, _ = fmt.Fprintf(w.W, format, args...)
}

func (w *Writer) IsOutputCurrent(index int) bool {
	return w.Index == index
}

func (w *Writer) GetOutputModule(index int) string {
	return w.Outputs[index].Module
}

func (w *Writer) Close() error {
	return w.W.(io.Closer).Close()
}
